const chatLoadErrors = {
  'permission-denied': "You don't have permission to load chats",
  'failed-precondition': 'Setting things up, please try again in a few minutes',
  unavailable: 'You appear to be offline',
};

export const messengerStrings = {
  retry: 'Retry',
  chatsCouldNotLoad: 'Chats could not be loaded. Please try again.',
  profilesCouldNotLoad: 'Chat profiles could not be loaded. Please try again.',
  peopleCouldNotLoad: 'People could not be loaded. Please try again.',
  couldNotStartChat: 'Could not start this chat. Check your connection and database access.',
  couldNotMarkChatsRead: 'Could not update chats. Please try again.',
  chatsTitle: 'Chats',
  contactsTitle: 'Contacts',
  chatDetails: 'Chat details',
  contactActions: 'Contact actions',
  profile: 'Profile',
  mute: 'Mute',
  search: 'Search',
  chatInfo: 'Chat info',
  chatInfoDescription: 'Conversation details and shared settings.',
  customizeChat: 'Customize chat',
  chatTheme: 'Theme and chat settings',
  mediaAndFiles: 'Media and files',
  sharedMedia: 'Photos and shared files',
  privacyAndSupport: 'Privacy & support',
  privacyAndSafety: 'Privacy and safety',
  signInToSeeContacts: 'Sign in to see your contacts.',
  moreOptions: 'More options',
  closeOptions: 'Close options',
  clearSearch: 'Clear search',
  markAllRead: 'Mark all as read',
  markingRead: 'Marking chats as read…',
  openMessenger: 'Open full Messenger',
  newMessage: 'New message',
  chatsButton: 'Chats',
  searchMessenger: 'Search Messenger',
  allChats: 'All',
  unreadChats: 'Unread',
  groupChats: 'Groups',
  people: 'People',
  findSomeone: 'Find someone',
  noChatsYet: 'No chats yet',
  noUnreadChats: 'No unread chats',
  noGroupChats: 'No group chats',
  noMatchingChats: 'No matching chats',
  searchToStart: 'Search for someone to start a conversation',
  noMatchingPeople: 'No people found',
  searchingPeople: 'Searching people…',
  seeAllMessenger: 'See all in Messenger',
  loadingChats: 'Loading chats',
  groupConversation: 'Group conversation',
  chatConversation: 'Conversation',
  codeWithSiamUser: 'CodeWithSiam user',
  activeNow: 'Active now',
  communityMember: 'CodeWithSiam member',
  openingChat: 'Opening…',
  getOpenChatLabel(name) {
    return `Open chat with ${name}`;
  },
  startNewChat: 'Start a new chat',
  newChat: 'New chat',
  searchChatsAndPeople: 'Search chats or people',
  backToChats: 'Back to chats',
  minimizeChat: 'Minimize chat',
  closeChat: 'Close chat',
  emojiPicker: 'Emoji picker',
  peopleSection: 'People',
  typingNow: 'Typing…',
  imageUploadProgress: 'Image upload progress',
  startConversation: 'Start the conversation',
  openingConversation: 'Opening conversation...',
  conversationUnavailable: 'Conversation unavailable.',
  selectChat: 'Select a chat',
  pickSomeoneToStart: 'Pick someone from the left to start a conversation',
  unreadCount(count) {
    return `${count} unread`;
  },
  yourConversations: 'Your conversations',
  recentChats: 'Recent chats',
  messageAction: 'Message',
  noPeopleForSearch(term) {
    return `No people found for “${term}”.`;
  },
  peopleSearchUnavailable: 'People search is unavailable right now.',
  you: 'You',
  today: 'Today',
  dateUnavailable: 'Date unavailable',
  offline: 'Offline',
  lastSeenJustNow: 'Last seen just now',
  lastSeenMinutes(minutes) {
    return `Last seen ${minutes}m ago`;
  },
  lastSeenHours(hours) {
    return `Last seen ${hours}h ago`;
  },
  lastSeenDate(date) {
    return `Last seen ${date}`;
  },
  imageUnavailable: 'Image unavailable',
  openImage: 'Open image',
  sharedImage: 'Shared image',
  messageListenerFailed: 'Messages could not be loaded. Check your connection and database access.',
  waitForCurrentMessage: 'Wait for the current message to finish sending.',
  waitBeforeSending: 'Please wait a moment before sending another message.',
  waitOneSecond: 'Please wait a second before sending another message.',
  messageLimit: 'Messages can be up to 2,000 characters.',
  messageSendFailed: 'Message failed to send. Use Retry to try again.',
  messagePermissionDenied: "You don't have permission to send messages in this chat.",
  messageOffline: 'You appear to be offline. Check your connection and retry.',
  messageDeliveredPreviewFailed: 'Message sent, but the chat preview could not be updated.',
  imageUnavailableForSending: 'This image could not be used.',
  onlySupportedImages: 'Only JPG, PNG, WebP or GIF images up to 5MB are allowed',
  imagesTooLarge: 'Images must be 5MB or smaller.',
  imageProcessingFailed: 'Image processing failed. Please choose another image.',
  captionLimit: 'Captions can be up to 2,000 characters.',
  uploadCanceled: 'Upload canceled. Select Retry to continue.',
  imageUploadFailed: 'Image upload failed. Check your connection and try again.',
  olderMessagesFailed: 'Older messages could not be loaded.',
  messageDeleteFailed: 'Message could not be deleted.',
  messageCopied: 'Message copied.',
  copyFailed: 'Copy failed.',
  dropImage: 'Drop an image to attach',
  loading: 'Loading...',
  loadOlderMessages: 'Load older messages',
  messageDeleted: 'This message was deleted',
  deletedMessage: 'Message deleted',
  notSent: 'Failed to send ·',
  sent: 'Sent',
  seen: 'Seen',
  sending: 'Sending',
  copy: 'Copy',
  reply: 'Reply',
  photo: 'Photo',
  more: 'More',
  deleteForMe: 'Delete for me',
  deleteForEveryone: 'Delete for everyone',
  otherPersonTyping: 'Other person is typing',
  newMessages: 'New messages',
  imagePreview: 'Image preview',
  uploadingImage(percent) {
    return `Uploading image ${percent}%`;
  },
  imageReady: 'Image ready to send',
  retryUpload: 'Retry upload',
  cancelImageUpload: 'Cancel image upload',
  removeImage: 'Remove image',
  cancelUpload: 'Cancel upload',
  chooseEmoji: 'Choose emoji',
  attachImage: 'Attach image',
  addCaption: 'Add a caption...',
  typeMessage: 'Type a message...',
  messageLabel: 'Message',
  sendImage: 'Send image',
  sendMessage: 'Send message',
  closeImage: 'Close image',
  enlargedImage: 'Shared image enlarged',
  cancelReply: 'Cancel reply',
  replyingTo: 'Replying to',
  yourself: 'yourself',
  replyMessage: 'message',
  replyToMessage(text) {
    return `Replying to ${text}`;
  },
  peopleSearchDescription: 'Search for someone to start a conversation',
  loadingContacts: 'Loading contacts',
  noContacts: 'No contacts yet',
  findContacts: 'Search for someone to start a conversation',
  yesterday: 'Yesterday',
  now: 'Now',
  getChatLoadError(code) {
    const normalizedCode = String(code || '').toLowerCase().replaceAll('_', '-');
    return chatLoadErrors[normalizedCode] || messengerStrings.chatsCouldNotLoad;
  },
};
